version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
          time: '06:00'
          timezone: 'America/Chicago'
    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: 'daily'
          time: '07:00'
          timezone: 'America/Chicago'
