name: Package Libraries

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: yarn

            - name: Install
              shell: pwsh
              run: yarn install

            - name: Package
              shell: pwsh
              run: yarn run package

            - name: Upload Artifacts
              uses: actions/upload-artifact@v3.1.3
              with:
                  path: '_InstallPackages/**/*.zip'
                  if-no-files-found: error
                  retention-days: 90
