name: Package Libraries

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: yarn

            - name: Install
              shell: pwsh
              run: yarn install

            - name: Package
              shell: pwsh
              run: yarn run package

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4.4.0
              with:
                  path: '_InstallPackages/**/*.zip'
                  if-no-files-found: error
                  retention-days: 90
